version: "3.3"

services:

  # Discovery Service
  discovery-service:
    image: bmagario/discovery-service-image:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    network_mode: host

  # Gateway Service
  gateway-service:
    image: bmagario/gateway-service-image:latest
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    environment:
      WAIT_HOSTS: localhost:8761
    network_mode: host

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: microservices
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    network_mode: host

  redis:
    image: redis
    ports:
      - "6379:6379"
    network_mode: host

  # Main Service (sum-calculator-service)
  sum-calculator-service:
    image: bmagario/sum-calculator-service-image:latest
    depends_on:
      - discovery-service
      - gateway-service
      - postgres
      - redis
    environment:
      WAIT_HOSTS: localhost:8080
    deploy:
      mode: replicated
      replicas: 2
    network_mode: host

  # Percentage Service
  percentage-service:
    image: bmagario/percentage-service-image:latest
    depends_on:
      - discovery-service
      - gateway-service
    environment:
      WAIT_HOSTS: localhost:8080
    deploy:
      mode: replicated
      replicas: 2
    network_mode: host