version: "3.3"

services:

  # Discovery Service
  discovery-service:
    build: discovery-service
    image: discovery-service-image:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - microservices-challenge

  # Gateway Service
  gateway-service:
    build: gateway-service
    image: gateway-service-image:latest
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    networks:
      - microservices-challenge

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: microservices
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    networks:
      - microservices-challenge

  # Main Service (sum-calculator-service)
  #sum-calculator-service:
  #  build: sum-calculator-service
  #  image: sum-calculator-service-image:latest
  #  ports:
  #    - "9090:9090"
  #  depends_on:
  #    - discovery-service
  #    - gateway-service
  #    - postgres
  #  networks:
  #    - microservices-challenge

  # Percentage Service
  #percentage-service:
  #  build: percentage-service
  #  image: percentage-service-image:latest
  #  ports:
  #    - "7070:7070"
  #  depends_on:
  #    - discovery-service
  #    - gateway-service
  #  networks:
  #    - microservices-challenge

networks:
  microservices-challenge:
    driver: bridge
